spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: yogesh17999@gmail.com
    password: bzcsmoocoxqqnqfg
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  application:
    name: clp-service

  datasource:
    url: jdbc:postgresql://localhost:5432/clp
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

#Personal credential
cloud:
  aws:
    credentials:
      accessKey: <key>
      secretKey: <secret>
    region:
      static: eu-north-1
    bucket:
      name: clp.files
      clp:
        folderName: contents
    url:
      expiration: 600000 #10 min

razorpay:
  api:
    key:
      id: <key>
      secret: <secret>
